services:
  backend:
      container_name: plantio-backend
      build:
        context: backend
      env_file: "backend/.env"
      networks:
        - default
        - frontend
      ports:
        - 8000:8000
      restart: unless-stopped
  frontend:
    container_name: plantio-frontend
    build:
      context: frontend
    networks:
      - frontend
    ports:
      - 4000:3002
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"